# Site Settings

# Most search engines will truncate Page title to 65 characters.
title: Jekyll Business Sense

# Try to get up to 230 characters
# Note that most search engines will truncate to 160 characters
description: >-
  Proudly serving the community since 2018

# used in LocalBusiness schema, and Open Graph
# store in src/_assets/images
logo: jekyll-logo.png
analytics-id:
opengraph:
  fb-appid:
  fb-user: jekyll-business-sense
  image: # override site.logo (store in src/_assets/images)

url: "https://jekyll-business-sense.burden.cc" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
thanks: "/thanks" # after form submitted, send visitor here
github: burden/jekyll-business-sense

# Build settings
plugins:
  - jekyll-assets
  - kramdown
  - uglifier

source: src
destination: www
markdown: kramdown

compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
